CREATE DATABASE servlet0229 CHARSET utf8mb4;
USE servlet0229;
CREATE TABLE users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(255) NOT NULL UNIQUE,
  nickname VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);